FROM ubuntu:latest
#
# Now install the needed python packages
RUN apt-get -y update && apt-get install -y net-tools python3 gcc
RUN apt-get install -y python3-dev python3-pip
RUN python3 -m pip install --upgrade pip
RUN pip3 install kafka-python
RUN pip3 install Pillow
RUN mkdir gifs

#
# Next, copy our compiler code into container image
COPY images_to_gif.py /
