apiVersion: apps/v1
kind: Deployment        
metadata:
  name: gif-compiler-deployment  # A name must be given to the Job type in the metadata section
spec:
  selector:
    matchLabels:
      app: gif-compiler-app
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: gif-compiler-app  # this is used in our service yaml file to match with the pod
    spec:                 # actual specification
      hostname: gif-compiler-host
      nodeSelector:  # this shows how you force k8s to schedule the pod on a specified node
        kubernetes.io/hostname: kubemaster
      containers:
        - name: gif-compiler      # this is going to be used for DNS name
          # Change the IP address to where you are running this
          image: 129.114.25.94:5000/gif-compiler   # this is the image in registry accessible
                                             # from all our workers
          imagePullPolicy: Always  # This forces the node to pull the image
          command: ["python3"]
          args: ["/images_to_gif.py"]
      restartPolicy: Always
