---
  - name: "Play 1: Creating new Chameleon VMs"
    hosts: MyLocalVMs
    remote_user: cc
    collections:
      - openstack.cloud

    tasks:
    - include_tasks: tasks/create_cc_vm2.yml
    - include_tasks: tasks/create_cc_vm3.yml
    - name: Pause for 2 minute to allow setup to complete
      pause:
           minutes: 2

  - name: "Play 2: Setting Up Environment"
    hosts: MyChameleonVMs
    remote_user: cc
    become: yes
    collections:
      - openstack.cloud

    tasks:
#    - include_tasks: tasks/install_packages.yml
    - include_tasks: tasks/add_ufw_rules.yml

...