---
  - name: "Play 1: Creating new Chameleon VMs"
    hosts: MyLocalVMs
    remote_user: cc
    collections:
      - openstack.cloud

    tasks:
    - include_tasks: setup_tasks/create_cc_vm2.yml
    - include_tasks: setup_tasks/create_cc_vm3.yml
    - name: Pause for 2 minute to allow setup to complete
      pause:
           minutes: 2

  - name: "Play 2: Setting Up Environment"
    hosts: MyChameleonVMs
    remote_user: cc
    become: yes
    collections:
      - openstack.cloud

    tasks:
#    - include_tasks: setup_tasks/install_packages.yml
    - include_tasks: setup_tasks/add_ufw_rules.yml

  - name: "Play 3: Setting up Docker"
    hosts: MyChameleonVMs
    remote_user: cc
    become: yes
    collections:
      - openstack.cloud

    tasks:
    - include_tasks: setup_tasks/install_docker.yml
    - include_tasks: setup_tasks/configure_docker.yml
    - include_tasks: setup_tasks/disabling_swap.yml

  - name: "Play 3: Setting up Kubernetes"
    hosts: MyChameleonVMs
    remote_user: cc
    become: yes
    collections:
      - openstack.cloud

    tasks:
    - include_tasks: setup_tasks/install_kubernetes.yml
    - include_tasks: setup_tasks/add_hostname_VM2.yml
      when: inventory_hostname == ansible_play_hosts[1]
    - include_tasks: setup_tasks/add_hostname_VM3.yml
      when: inventory_hostname == ansible_play_hosts[0]

...