apiVersion: apps/v1
kind: Deployment        
metadata:
  name: raytrace-worker-deployment  # A name must be given to the Job type in the metadata section
spec:
  replicas: 5              
  selector:
    matchLabels:
      app: raytrace-worker-app
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: raytrace-worker-app  # this is used in our service yaml file to match with the pod
    spec:                 # actual specification
      hostname: raytrace-worker-host
      nodeSelector:  # this shows how you force k8s to schedule the pod on a specified node
        kubernetes.io/hostname: team6-ansiblevm3
      containers:
        - name: raytrace-worker      # this is going to be used for DNS name
          # Change the IP address to where you are running this
          image: 129.114.25.94:5000/raytracer   # this is the image in registry accessible
                                             # from all our workers
          imagePullPolicy: Always  # This forces the node to pull the image
          command: ["bash"]
          args: ["/run_raytracer.sh"]
      restartPolicy: Always
