apiVersion: apps/v1
kind: Deployment         # We are testing the Job resource type
metadata:
  name: zookeeper-deployment  # A name must be given to the Job type in the metadata section
spec:                     # This is the specification where we can even put the number of replicas
  selector:
    matchLabels:
      app: zookeeper-app  
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: zookeeper-app  # this is used in our service yaml file to match with the pod
    spec:                 # actual specification
      hostname: zookeeper-host
      nodeSelector:  # this shows how you force k8s to schedule the pod on a specified node
        kubernetes.io/hostname: kubemaster
      containers:
        - name: zookeeper      # this is going to be used for DNS name
          # Change the IP address to where you are running this
          image: 129.114.25.94:5000/kafka_zookeeper   # this is the image in registry accessible
                                             # from all our workers
          imagePullPolicy: Always  # This forces the node to pull the image
          command: ["kafka/bin/zookeeper-server-start.sh"]
          args: ["kafka/config/zookeeper.properties"]  # arguments to run. 
      restartPolicy: Always  
